In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/email.csv')

In [3]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.describe()

       Category                 Message
count      5573                    5573
unique        3                    5158
top         ham  Sorry, I'll call later
freq       4825                      30

In [5]:
df.shape

(5573, 2)

In [6]:
df.dtypes

Category    str
Message     str
dtype: object

In [7]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [8]:
df[df['Category'] == '{"mode":"full"']

            Category          Message
5572  {"mode":"full"  isActive:false}

In [9]:
df['Category'].unique()

<ArrowStringArray>
['ham', 'spam', '{"mode":"full"']
Length: 3, dtype: str

In [10]:
df[df['Category'] != 'ham'][df['Category'] != 'spam']

/tmp/ipykernel_11585/1458601964.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Category'] != 'ham'][df['Category'] != 'spam']

            Category          Message
5572  {"mode":"full"  isActive:false}

### Notes

#### Row 5572 needs to be removed